spring:
  config:
    activate:
      on-profile: local

my-app:
  welcome-message: "Hello, Local!!"

---

spring:
  config:
    activate:
      on-profile: dev

my-app:
  welcome-message: "Hello, Dev!!"